spring:
  ai:
    openai:
      api-key: ${OPENAI_APIKEY}
      audio:
        transcription:
          options:
            model: whisper-1         
  servlet:
    multipart:
      max-file-size:
        25MB
      max-request-size:
        25MB    